NUMPY:

Numpy is a python package. It stands for "Numerical Python". It is library consisting of multdimensional array objects and a collection of routines for processing of array.

Operations :
1. Mathematics and logical operations on arrays.
2. Fourier transforms and routines for shape manipulation.
3. Operations related to linear algebra. Nupy has in-built functions for linear algebra and random number generation. 

Numpy is often used along with packages like SciPy (scientific Python) and Mat-plotlib(plotting library)

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.0'

In [4]:
l=[10,11,12,13,14,15]
l2=np.array(l)
print(l2)
print("adding the numbers : ",l2+10)

[10 11 12 13 14 15]
adding the numbers :  [20 21 22 23 24 25]


In [5]:
#list
arr_1=[1,2,3,4]
arr_2=[5,6,7,8]
for i in range(4):
    print(arr_1[i]+arr_2[i],end=" ")
    
        

6 8 10 12 

In [8]:
# array
arr_1=[1,2,3,4]
arr_2=[5,6,7,8]
arr_1_narr=np.array([1,2,3,4])
arr_2_narr=np.array(arr_2)
print(arr_1_narr+arr_2_narr)

[ 6  8 10 12]


In [ ]:
a=50
print("type :",type(a))
print("ndimenstion :",a.ndim) # error
print("shape :",a.shape)      # error


type : <class 'int'>


'print("ndimenstion :",a.ndim) # error\nprint("shape :",a.shape)      # error'

In [10]:
a=np.array([1,2,3,4])
print(a)
print("type :",type(a))
print("ndimenstion :",a.ndim)
print("shape :",a.shape)

[1 2 3 4]
type : <class 'numpy.ndarray'>
ndimenstion : 1
shape : (4,)


In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print("type :",type(b))
print("ndimenstion :",b.ndim)
print("shape :",b.shape)

[[1 2 3]
 [4 5 6]]
type : <class 'numpy.ndarray'>
ndimenstion : 2
shape : (2, 3)


In [12]:
# minimum dimensions
c=np.array([1,2,3,4,5,6],ndmin=2)
print(c)
print("type :",type(c))
print("ndimenstion :",c.ndim)
print("shape :",c.shape)

[[1 2 3 4 5 6]]
type : <class 'numpy.ndarray'>
ndimenstion : 2
shape : (1, 6)


In [13]:
a=np.arange(25)
print(a)
print("type :",type(a))
print("ndimenstion :",a.ndim)
print("shape :",a.shape)
print("itemsize :",a.itemsize)
print(a.reshape(5,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
type : <class 'numpy.ndarray'>
ndimenstion : 1
shape : (25,)
itemsize : 4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
a=np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# Creating Arrays 
one dimenstional array

In [15]:
b=np.empty(5)
print(b)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34609111e-307
 2.12199585e-314]


In [16]:
a=np.random.rand(1,5)
print(a)

[[0.14974426 0.29749939 0.9271355  0.93947083 0.39675063]]


In [17]:
a=np.random.uniform(1,99,7)
print(a)

[ 6.0077786  79.61471426 68.88766684 76.4838453  27.47065274 91.84440411
 66.51134763]


In [18]:
a=np.random.normal(1,99,4)
print(a)

[-89.82657907  47.44265632 -42.45681062  42.02578735]


In [19]:
a=np.random.randint(1,99,3)
print(a)



[93 77 12]


In [20]:
print(np.sort(a))



[12 77 93]


In [21]:
b=np.arange(0,10,2)
print(b)

[0 2 4 6 8]


In [22]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.zeros((3,))

array([0., 0., 0.])

In [24]:
np.zeros((1,2),dtype=int)

array([[0, 0]])

In [25]:
np.zeros((1,2))

array([[0., 0.]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((1,))

array([1.])

In [28]:
np.ones((1,3))

array([[1., 1., 1.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.diag([3,3,6])

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [32]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


Slicing 2D

In [33]:
a[0]

array([10, 20, 30])

In [34]:
a[1]=[11,12,13]
a

array([[10, 20, 30],
       [11, 12, 13],
       [70, 80, 90]])

In [35]:
a[2,2]=200
a

array([[ 10,  20,  30],
       [ 11,  12,  13],
       [ 70,  80, 200]])

In [36]:
a[0:3,1:3]

array([[ 20,  30],
       [ 12,  13],
       [ 80, 200]])

In [37]:
a[1:3]

array([[ 11,  12,  13],
       [ 70,  80, 200]])

In [38]:
l=[1,2,3,4,5,6]
l1=[]
for i in l :
    if i%2!=0:
        l1.append(i)
print(l1)

[1, 3, 5]


In [39]:
l=np.array([1,2,3,4,5,6])
print(l[l%2!=0])

[1 3 5]


In [40]:
l=[2,4,6,8,10]
l2=[1,0,-1]
for i in  l2:
    print(l[i],end=" ")

4 2 10 

In [41]:
l=np.array([2,4,6,8,10])
print(l[[1,0,-1]])

[ 4  2 10]


In [42]:
l=[23,34.6,565,686,73,4]
for i in l:
    if i%2==0:
        print("True")
    else:
        print('Flase')

Flase
Flase
Flase
True
Flase
True


In [43]:
l=np.array([23,34.6,565,686,73,4])
print(l%2==0)

[False False False  True False  True]


# Acessing elements / extracting the values.

Single value --> indexing

In [44]:
a=np.arange(1,99,8)
print(a)
a[-1]

[ 1  9 17 25 33 41 49 57 65 73 81 89 97]


97

In [45]:
a[3]

25

multiple value --> index



In [46]:
a[[-1,2,-2]]

array([97, 17, 89])

multiple value --> slicing

In [47]:
a[0:4:1]

array([ 1,  9, 17, 25])

In [48]:

a[4:1:-1]

array([33, 25, 17])

multiple value --> condition

In [49]:
a=np.random.randint(1,99,24)

In [50]:
print(a[a%2!=0])

[57 65 35 19 83 69 53  5]


Modification of array

append

In [51]:
a=np.append(a,123)
print(a)

[ 57  94  80  65  14  18  86  35  98  90  10  19  83  12  44  16  69  53
  52  84  50  44   5  42 123]


deleting (pop)

In [52]:
a=np.delete(a,6)
print(a)


[ 57  94  80  65  14  18  35  98  90  10  19  83  12  44  16  69  53  52
  84  50  44   5  42 123]


In [53]:
a=np.delete(a,[2,3])
print(a)

[ 57  94  14  18  35  98  90  10  19  83  12  44  16  69  53  52  84  50
  44   5  42 123]


swallow copy


In [54]:
a=np.array([1,2,3])
b=a.copy()
print(a)
print(b)

[1 2 3]
[1 2 3]


In [55]:
a=np.array([1,2,3])
b==a
print(a)
print(b)

[1 2 3]
[1 2 3]


# Array Manipulation


| Array Manipulation | `array.reshape()`                       | Reshape the array.                                   |
|                           | `numpy.vstack()`                        | Stack arrays vertically.                             |
|                           | `numpy.hstack()`                        | Stack arrays horizontally.                           |
|                           | `numpy.split()`                         | Split an array into multiple sub-arrays.            |
|                           | `numpy.transpose()`                     | Transpose the array.                                 |
|                           | `numpy.concatenate()`         

In [56]:
a=np.array([1,2,3,4,5,6,7,8],ndmin=2)
print(a)

[[1 2 3 4 5 6 7 8]]


In [ ]:
a=np.array([[11,12,13,14,15],[16,17,18,19,20]])
b=a.ravel()
print(b)

[ 11 122  13  14  15  16  17  18  19  20]


In [82]:
# sorting along an axis =1 --> row  and axis =0 --> column
a=np.array([[13,14,15,11,12],[19,20,16,17,18],[12,63,45,67,345]])
b=np.sort(a)
print(b)

[[ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 12  45  63  67 345]]


In [83]:
a=np.array([[13,14,15,11,12],[19,20,16,17,18],[12,63,45,67,345]])
b=np.sort(a,axis=0)
print(b)

[[ 12  14  15  11  12]
 [ 13  20  16  17  18]
 [ 19  63  45  67 345]]


In [88]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[2,3],[4,5],[6,7]])
c=a*b
print("***multiplication***")
print(c)
c=a+b
print("***addition***")
print(c)
c=a-b
print("***subtraction***")
print(c)
c=a/b
print("***division***")
print(c)

***multiplication***
[[ 2  6]
 [12 20]
 [30 42]]
***addition***
[[ 3  5]
 [ 7  9]
 [11 13]]
***subtraction***
[[-1 -1]
 [-1 -1]
 [-1 -1]]
***division***
[[0.5        0.66666667]
 [0.75       0.8       ]
 [0.83333333 0.85714286]]


In [95]:
#matrics multiplications
a=np.array([[1,2,3,4],[2,3,4,5]])
b=np.array([[12,34,56,7],[67,34,12,45]])
c=np.matmul(a,b.T)
print(c)


[[276 351]
 [385 509]]


In [97]:
print(a)
print(b)

[[1 2 3 4]
 [2 3 4 5]]
[[12 34 56  7]
 [67 34 12 45]]


In [ ]:
#concatenate
np.concatenate((a,b),axis=0) # column

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [12, 34, 56,  7],
       [67, 34, 12, 45]])

In [100]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [12, 34, 56,  7],
       [67, 34, 12, 45]])

In [101]:
np.concatenate((a,b),axis=1) # row

array([[ 1,  2,  3,  4, 12, 34, 56,  7],
       [ 2,  3,  4,  5, 67, 34, 12, 45]])

In [102]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 12, 34, 56,  7],
       [ 2,  3,  4,  5, 67, 34, 12, 45]])

# Operations
arthematic operation
comparition operation


In [58]:
x=np.random.randint(1,25,6)
y=np.random.randint(1,25,6)
print("add :",x+y)
print("sub :",x-y)
print("mult :",x*y)
print("div :",x/y)
print("mod :",x%y)

add : [38 11 22 23 39 27]
sub : [ 8 -5 16 -7  9  7]
mult : [345  24  57 120 360 170]
div : [1.53333333 0.375      6.33333333 0.53333333 1.6        1.7       ]
mod : [8 3 1 8 9 7]


Comparision Operations

In [59]:
n=np.random.uniform(1,75,5)
m=np.random.uniform(1,75,5)
print("equal to:",n==m)
print("greater than equal to :",n>=m)
print("less than equal to :",n<=m)
np.array_equal(n,m)

equal to: [False False False False False]
greater than equal to : [ True False False False  True]
less than equal to : [False  True  True  True False]


False

Mathematical Operations

In [60]:
a=np.array([1,2,3,4,5])
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [61]:
np.max(a)

5

In [62]:
np.min(a)

1

In [63]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [64]:
b=np.array([5,6,7,8,9])
a=np.array([1,2,3,4,5])
np.dot(a,b)

115

In [65]:
np.divide(a,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [66]:
np.multiply(a,3)

array([ 3,  6,  9, 12, 15])

In [67]:
np.sum(a)

15

In [68]:
np.sin(b)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [69]:
np.cos(b)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [70]:
import warnings
warnings.simplefilter("ignore")


Statistical Operations

In [71]:
np.histogram(b)


(array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1], dtype=int64),
 array([5. , 5.4, 5.8, 6.2, 6.6, 7. , 7.4, 7.8, 8.2, 8.6, 9. ]))

In [72]:
np.corrcoef(b)

1.0

In [73]:
np.cov(b)

array(2.5)

In [74]:
np.mean(b)

7.0

In [75]:
np.median(b)

7.0

In [76]:
np.std(b)

1.4142135623730951